apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:ankouros/samakia-gitops.git'
    targetRevision: main
    path: argo/apps/jenkins
    helm:
      chart: jenkins
      values: |
        controller:
          installPlugins:
            - kubernetes:1.30.1
            - workflow-aggregator:2.6
          ingress:
            enabled: true
            hostname: jenkins.samakia.lab
            tls: true
            annotations:
              nginx.ingress.kubernetes.io/backend-protocol: HTTPS
              nginx.ingress.kubernetes.io/ssl-redirect: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
