apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:ankouros/samakia-gitops.git'
    targetRevision: main
    path: argo/apps/jenkins  # Path where the Jenkins Helm release file is located
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: jenkins  # Namespace where Jenkins will be deployed
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
