controller:
  adminUser: admin
  adminPassword: admin
  serviceType: NodePort
  servicePort: 8080
  serviceNodePort: 32099
  persistence:
    enabled: true
    storageClass: "nfs-client"
    size: 8Gi
