apiVersion: tekton.dev/v1beta1
kind: Configuration
metadata:
  name: tekton-config
  namespace: tekton-pipelines
spec:
  # Enable Tekton Pipelines feature
  pipelines:
    # Enable or disable the feature
    featureFlags:
      enableAPIFields: true   # Enables new API fields for Tekton resources
      enableTektonMetrics: true   # Enables Prometheus metrics collection
      enableTektonDashboard: true   # Enables the Tekton Dashboard (optional)
      enableTektonTriggers: true   # Enables Tekton Triggers for event-driven pipelines
  
  # Configures the default task and pipeline resources for the pipelines
  defaultTaskResources:
    requests:
      cpu: "100m"  # Default CPU request for tasks
      memory: "256Mi"  # Default memory request for tasks
    limits:
      cpu: "500m"  # Default CPU limit for tasks
      memory: "1Gi"  # Default memory limit for tasks
  
  # Configure default pipeline resources like the service account used to run Tekton tasks
  defaultServiceAccount: tekton-pipelines-sa

  # Enable Tekton Metrics (Prometheus)
  metrics:
    prometheus:
      enable: true
      port: 9090   # Port to expose Prometheus metrics (default is 9090)
  
  # Configure the default resource for pipelines
  taskRun:
    timeout: "1h"  # Default timeout for task runs
  pipelineRun:
    timeout: "1h"  # Default timeout for pipeline runs
  
  # PipelineRunner for running pipelines
  pipelineRunner:
    image: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/pipelinerun
    imagePullPolicy: IfNotPresent

  # Configure the Tekton Triggers (for event-driven pipelines)
  triggers:
    enable: true
    eventListener:
      image: gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/trigger
      imagePullPolicy: IfNotPresent

  # Configure Tekton Dashboard settings (if enabled)
  dashboard:
    enable: true
    url: "http://tekton-dashboard.tekton-pipelines.svc.cluster.local"  # Adjust if needed
    port: 9097  # Adjust the port for the dashboard service

  # Tekton Hub Configuration (optional if you are using Tekton Hub for sharing resources)
  hub:
    enable: true
    url: "https://hub.tekton.dev"  # Adjust if you have a local Tekton Hub
