apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: argocd-update-image
  annotations:
    description: "Updates image tags in ArgoCD applications"
spec:
  params:
    - name: application
      description: ArgoCD application name
      type: string
    - name: image
      description: Full image reference (registry/repo:tag)
      type: string
    - name: argocd-server
      description: ArgoCD server address
      type: string
      default: "argocd-server.argocd.svc.cluster.local:443"

  workspaces:
    - name: manifest-dir
      description: Directory containing Kubernetes manifests

  steps:
    - name: update-image
      image: argoproj/argocd-cli:latest
      env:
        - name: ARGOCD_TOKEN
          valueFrom:
            secretKeyRef:
              name: argocd-api-token
              key: token
      script: |
        #!/bin/sh
        cd $(workspaces.manifest-dir.path)
        argocd login $(params.argocd-server) \
          --grpc-web \
          --insecure \
          --username admin \
          --password $ARGOCD_TOKEN
        
        argocd app set $(params.application) \
          --helm-set image.tag=$(params.image.split(':')[1]) \
          --helm-set image.repository=$(params.image.split(':')[0])
        
        argocd app sync $(params.application) --prune