apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-and-push-cached
spec:
  params:
    - name: image
      type: string
    - name: cache-repo
      description: Repository to store cache layers
      type: string
      default: ""

  workspaces:
    - name: source
    - name: docker-config

  steps:
    - name: build-with-cache
      image: gcr.io/kaniko-project/executor:v1.9.1
      securityContext:
        runAsUser: 0
      env:
        - name: DOCKER_CONFIG
          value: "/workspace/docker-config"
      command:
        - /kaniko/executor
      args:
        - --dockerfile=$(params.dockerfile)
        - --context=$(workspaces.source.path)
        - --destination=$(params.image)
        - --cache=$(if(params.cache-repo != '', 'true', 'false'))
        - --cache-repo=$(params.cache-repo)
        - --cache-ttl=72h
        - --snapshotMode=redo
        - --use-new-run