apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: notify-slack
  namespace: tekton-pipelines
spec:
  params:
    - name: webhook-url
      type: string
      description: Slack Webhook URL to send the message to
    - name: message
      type: string
      description: The message to send to Slack
  steps:
    - name: send-notification
      image: curlimages/curl:latest  # Use curl to send the message
      script: |
        #!/bin/sh
        curl -X POST -H 'Content-type: application/json' --data '{
          "text": "$(params.message)"
        }' $(params.webhook-url)
      resources: {}
