apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: vulnerability-scan
  annotations:
    description: "Scans container images for vulnerabilities using Trivy"
spec:
  params:
    - name: image
      description: Image reference to scan
      type: string
    - name: severity
      description: Minimum severity level (UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL)
      type: string
      default: "HIGH"
    - name: exit-code
      description: Exit code when vulnerabilities are found
      type: string
      default: "1"

  results:
    - name: VULNERABILITIES
      description: JSON report of found vulnerabilities
    - name: VULN-COUNT
      description: Count of vulnerabilities found

  steps:
    - name: scan
      image: aquasec/trivy:latest
      securityContext:
        privileged: true
      script: |
        #!/bin/sh
        trivy image --security-checks vuln \
          --severity $(params.severity) \
          --format json \
          --exit-code $(params.exit-code) \
          $(params.image) > /tekton/results/VULNERABILITIES
        
        # Count vulnerabilities
        jq '.Results[].Vulnerabilities | length' /tekton/results/VULNERABILITIES > /tekton/results/VULN-COUNT