apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: your-registry/users
  newTag: latest
patches:
- target:
    kind: Deployment
    name: users
  patch: |
    - op: replace
      path: /spec/replicas
      value: 3
