apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs
provisioner: example.com/nfs
parameters:
  server: 192.168.11.30
  path: /mnt/global_storage
reclaimPolicy: Delete
volumeBindingMode: Immediate
