apiVersion: apps/v1
kind: Deployment
metadata:
  name: birds
spec:
  replicas: 2
  selector:
    matchLabels:
      app: birds
  template:
    metadata:
      labels:
        app: birds
    spec:
      containers:
      - name: birds
        image: your-registry/birds:latest
