apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
  namespace: grafana
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`grafana.samakia.lab`)
      kind: Rule
      services:
        - name: grafana
          port: 80
  tls:
    secretName: samakia-wildcard-tls
