# argo/apps/grafana/values.yaml

## Grafana Main Configuration
adminUser: admin
adminPassword: "admin"  # Change to use secret reference in production
disableLoginForm: false

## Security
security:
  adminPassword: "admin"  # Override with Kubernetes secret in production
  disableInitialAdminCreation: false
  secret:
    existingSecret: ""  # Set to existing secret name if using external secrets
  disableGravatar: true

## Ingress Configuration
ingress:
  enabled: true
  className: "nginx"
  hosts:
    - grafana.samakia.lab
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  tls:
    - hosts:
        - grafana.samakia.lab
      secretName: "grafana-tls"

## Persistence
persistence:
  enabled: true
  type: pvc
  size: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: "standard"
  finalizers:
    - kubernetes.io/pvc-protection

## Resources
resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "2Gi"
    cpu: "1"

## Monitoring
serviceMonitor:
  enabled: true
  interval: 30s
  scrapeTimeout: 10s

## Dashboards Configuration
dashboards:
  default:
    enabled: true
    label: grafana_dashboard
    labelValue: "1"
    folder: /tmp/dashboards
  provider:
    allowUiUpdates: true
    foldersFromFilesStructure: true

## Datasources
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.monitoring.svc.cluster.local:9090
        access: proxy
        isDefault: true
        jsonData:
          timeInterval: "30s"
          httpMethod: "POST"
      - name: Loki
        type: loki
        url: http://loki.monitoring.svc.cluster.local:3100
        jsonData:
          maxLines: 1000

## Plugins
plugins:
  - grafana-piechart-panel
  - grafana-worldmap-panel
  - grafana-clock-panel

## Sidecar for automatic dashboard provisioning
sidecar:
  dashboards:
    enabled: true
    label: grafana_dashboard
    labelValue: "1"
    folder: /tmp/dashboards
    provider:
      allowUiUpdates: true
  datasources:
    enabled: true
    defaultDatasourceEnabled: true

## SMTP Configuration (for alerts)
smtp:
  existingSecret: "grafana-smtp"
  userKey: "user"
  passwordKey: "password"
  host: "smtp.example.com:465"
  fromAddress: "grafana@samakia.lab"

## Grafana Image
image:
  repository: grafana/grafana
  tag: 9.5.3
  pullPolicy: IfNotPresent

## Service Configuration
service:
  type: ClusterIP
  port: 3000
  targetPort: 3000
  annotations: {}
  labels: {}

## Additional Environment Variables
env:
  GF_FEATURE_TOGGLES_ENABLE: "traceToMetrics"
  GF_ALERTING_ENABLED: "true"
  GF_EXPLORE_ENABLED: "true"