apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ankouros/samakia-gitops.git
    targetRevision: main
    path: argo/apps/minio
    helm:
      releaseName: minio
      valuesObject:
        resources:
          limits:
            cpu: "2"
            memory: "4Gi"
          requests:
            cpu: "500m"
            memory: "2Gi"
        ingress:
          enabled: true
          host: "minio.samakia.lab"
          annotations:
            nginx.ingress.kubernetes.io/ssl-redirect: "true"
        consoleIngress:
          enabled: true
          host: "minio-console.samakia.lab"
  destination:
    server: https://kubernetes.default.svc
    namespace: samakia
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: minio
      namespace: samakia