apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: harbor
  namespace: harbor
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`harbor.samakia.lab`)
      kind: Rule
      services:
        - name: harbor
          port: 80
  tls:
    secretName: samakia-wildcard-tls
