apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: loki
  namespace: loki
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`loki.samakia.lab`)
      kind: Rule
      services:
        - name: loki
          port: 80
  tls:
    secretName: samakia-wildcard-tls
