groups:
- name: jenkins-alerts
  rules:
  - alert: JenkinsHighQueueLength
    expr: sum(jenkins_builds_queued_total{namespace="samakia"}) by (instance) > 5
    for: 5m
    labels:
      severity: warning
      component: jenkins
    annotations:
      summary: "Jenkins queue too long (instance {{ $labels.instance }})"
      description: "Jenkins queue length is {{ $value }} for more than 5 minutes"
      runbook_url: "https://example.com/runbooks/jenkins-queue"

  - alert: JenkinsBuildFailureRate
    expr: rate(jenkins_builds_failed_total{namespace="samakia"}[5m]) * 100 / rate(jenkins_builds_total{namespace="samakia"}[5m]) > 10
    for: 10m
    labels:
      severity: critical
      component: jenkins
    annotations:
      summary: "High Jenkins build failure rate (instance {{ $labels.instance }})"
      description: "Build failure rate is {{ $value | humanizePercentage }}% for more than 10 minutes"
      runbook_url: "https://example.com/runbooks/jenkins-failures"

  - alert: JenkinsNodeOffline
    expr: jenkins_node_offline{namespace="samakia"} == 1
    for: 2m
    labels:
      severity: warning
      component: jenkins
    annotations:
      summary: "Jenkins node offline (node {{ $labels.node }})"
      description: "Jenkins node {{ $labels.node }} has been offline for more than 2 minutes"
      runbook_url: "https://example.com/runbooks/jenkins-nodes"

  - alert: JenkinsHighMemoryUsage
    expr: (container_memory_working_set_bytes{namespace="samakia",container="jenkins"} / container_spec_memory_limit_bytes{namespace="samakia",container="jenkins"}) * 100 > 85
    for: 5m
    labels:
      severity: warning
      component: jenkins
    annotations:
      summary: "High Jenkins memory usage (instance {{ $labels.instance }})"
      description: "Jenkins memory usage is {{ $value | humanizePercentage }}% of limit"
      runbook_url: "https://example.com/runbooks/jenkins-memory"

  - alert: JenkinsHighCPUUsage
    expr: rate(container_cpu_usage_seconds_total{namespace="samakia",container="jenkins"}[5m]) / container_spec_cpu_quota{namespace="samakia",container="jenkins"} * 100 > 80
    for: 5m
    labels:
      severity: warning
      component: jenkins
    annotations:
      summary: "High Jenkins CPU usage (instance {{ $labels.instance }})"
      description: "Jenkins CPU usage is {{ $value | humanizePercentage }}% of limit"
      runbook_url: "https://example.com/runbooks/jenkins-cpu"

  - alert: JenkinsSCMErrors
    expr: increase(jenkins_scm_failures_total{namespace="samakia"}[1h]) > 5
    for: 0m
    labels:
      severity: warning
      component: jenkins
    annotations:
      summary: "Jenkins SCM errors detected (instance {{ $labels.instance }})"
      description: "{{ $value }} SCM failures in the last hour"
      runbook_url: "https://example.com/runbooks/jenkins-scm"

  - alert: JenkinsPluginErrors
    expr: increase(jenkins_plugin_errors_total{namespace="samakia"}[1h]) > 10
    for: 0m
    labels:
      severity: warning
      component: jenkins
    annotations:
      summary: "Jenkins plugin errors detected (instance {{ $labels.instance }})"
      description: "{{ $value }} plugin errors in the last hour"
      runbook_url: "https://example.com/runbooks/jenkins-plugins"

  - alert: JenkinsOutOfDiskSpace
    expr: jenkins_disk_usage_percent{namespace="samakia"} > 90
    for: 5m
    labels:
      severity: critical
      component: jenkins
    annotations:
      summary: "Jenkins disk space running low (instance {{ $labels.instance }})"
      description: "Disk usage is at {{ $value | humanizePercentage }}% capacity"
      runbook_url: "https://example.com/runbooks/jenkins-disk"