apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: tempo
  namespace: tempo
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`tempo.samakia.lab`)
      kind: Rule
      services:
        - name: tempo
          port: 80
  tls:
    secretName: samakia-wildcard-tls
