apiVersion: v2
name: vault
description: A Helm chart for HashiCorp Vault
type: application
version: 0.1.0
appVersion: "1.8.0"  # Version of Vault you are deploying
icon: https://www.hashicorp.com/favicon.ico
home: https://www.vaultproject.io
sources:
  - https://github.com/hashicorp/vault
maintainers:
  - name: HashiCorp
    email: support@hashicorp.com

dependencies:
  - name: vault
    version: 0.1.0
    repository: "https://helm.releases.hashicorp.com"
    condition: vault.enabled

# Values.yaml for configuring Vault deployment
values:
  # Configuration for Vault's Kubernetes service
  server:
    enabled: true
    replicaCount: 1
    resources:
      limits:
        memory: 1Gi
        cpu: 500m
      requests:
        memory: 512Mi
        cpu: 250m
    affinity: {}
    nodeSelector: {}
    tolerations: []

  # Configuration for Vault's Helm values
  vault:
    enabled: true
    service:
      type: ClusterIP
      port: 8200
    ingress:
      enabled: false
      path: /
      annotations: {}
      hosts:
        - vault.local.samakia.lab
    storage:
      haStorage:
        enabled: true
        size: 10Gi
        class: default
    initConfig: {}
    vaultConfig:
      ui: true
      api_addr: "http://localhost:8200"
      cluster_addr: "https://localhost:8201"
      listener:
        tcp:
          address: "0.0.0.0:8200"
          cluster_address: "0.0.0.0:8201"
          tls_disable: true
    authMethods:
      - type: kubernetes
        mount_path: /auth/kubernetes
        config:
          kubernetes_host: "https://kubernetes.default.svc"
          kubernetes_ca_cert: "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
          token_reviewer_jwt: "/var/run/secrets/kubernetes.io/serviceaccount/token"
          issuer: "https://kubernetes.default.svc.cluster.local"

  # Enable Vault UI and API
  ui:
    enabled: true

  # Enable Vault Auth methods
  authMethods:
    kubernetes:
      enabled: true

  # Configure Vault secret engines and policies
  secretEngines:
    - type: kv
      path: secret
      config:
        default_lease_ttl: "24h"
        max_lease_ttl: "72h"
    - type: pki
      path: pki
      config:
        default_lease_ttl: "24h"
        max_lease_ttl: "72h"

  # Configure Vault Agent Injector for Kubernetes
  vaultAgent:
    enabled: true
    injector:
      enabled: true
      # Default Vault Agent Kubernetes configuration
      config:
        sync: true
        secretInjectors:
          - secret_path: "secret/data/myapp/config"
            mount_path: "/etc/secrets"

  # Enable and configure Vault's KMS integration
  kms:
    enabled: true
    kmsProvider: AWS
    kmsConfig:
      accessKeyId: "your-access-key-id"
      secretAccessKey: "your-secret-access-key"
      region: "us-east-1"

  # Vault UI and API options
  ui:
    enabled: true
    serviceType: ClusterIP
    servicePort: 8200
    ingress:
      enabled: true
      annotations: {}
      hosts:
        - vault.local.samakia.lab
      path: /
      tls: false
