globalArguments:
  - --serversTransport.insecureSkipVerify
entryPoints:
  websecure:
    address: ":443"
additionalArguments:
  - --certificatesresolvers.myresolver.acme.tlsChallenge=true
  - --certificatesresolvers.myresolver.acme.email=admin@samakia.lab
  - --certificatesresolvers.myresolver.acme.storage=/data/acme.json
persistence:
  enabled: true
  size: 1Gi
