apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ankouros/samakia-gitops.git
    targetRevision: main
    path: infrastructure/bootstrap
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: users-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ankouros/samakia-gitops.git
    targetRevision: main
    path: services/users/kustomize/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: species-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ankouros/samakia-gitops.git
    targetRevision: main
    path: services/species/kustomize/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: birds-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ankouros/samakia-gitops.git
    targetRevision: main
    path: services/birds/kustomize/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pairs-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ankouros/samakia-gitops.git
    targetRevision: main
    path: services/pairs/kustomize/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portal-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ankouros/samakia-gitops.git
    targetRevision: main
    path: services/portal/kustomize/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
