grafana:
  adminPassword: admin
  persistence:
    enabled: true
    storageClassName: "nfs-client"
    size: 5Gi

prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: "nfs-client"
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
