apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-pipelines-role
  namespace: tekton-pipelines
  labels:
    app: tekton
    role: pipeline
spec:
  rules:
    - apiGroups: [""]
      resources: ["pods", "pods/exec", "services", "configmaps", "secrets", "endpoints"]
      verbs: ["get", "list", "create", "update", "patch", "delete"]
    - apiGroups: ["tekton.dev"]
      resources: ["pipelines", "pipelineruns", "tasks", "taskruns", "pipelinetriggers", "eventlisteners"]
      verbs: ["get", "list", "create", "update", "delete"]
    - apiGroups: ["rbac.authorization.k8s.io"]
      resources: ["roles", "rolebindings"]
      verbs: ["get", "list", "create", "update", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-pipelines-rolebinding
  namespace: tekton-pipelines
  labels:
    app: tekton
    role: pipeline
subjects:
  - kind: ServiceAccount
    name: tekton-pipelines-sa
    namespace: tekton-pipelines
roleRef:
  kind: Role
  name: tekton-pipelines-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-pipelines-sa
  namespace: tekton-pipelines
  labels:
    app: tekton
    role: pipeline

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tekton-pipelines-clusterrole
  labels:
    app: tekton
    role: pipeline
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get"]
  - apiGroups: ["tekton.dev"]
    resources: ["pipelines", "pipelineruns", "tasks", "taskruns", "pipelinetriggers", "eventlisteners", "resources"]
    verbs: ["get", "list", "create", "update", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-pipelines-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: tekton-pipelines-sa
    namespace: tekton-pipelines
roleRef:
  kind: ClusterRole
  name: tekton-pipelines-clusterrole
  apiGroup: rbac.authorization.k8s.io
