apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: git-trigger-template
  namespace: tekton-pipelines
spec:
  params:
    - name: git-repository-url
      description: The Git repository URL
    - name: git-repository-ref
      description: The Git branch or tag to checkout
    - name: git-commit
      description: The Git commit hash
    - name: git-author
      description: The author of the commit
    - name: git-message
      description: The commit message
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: git-pipeline-run-
      spec:
        pipelineRef:
          name: ci-cd-pipeline  # Name of the pipeline to trigger
        params:
          - name: git-repository-url
            value: "$(params.git-repository-url)"
          - name: git-repository-ref
            value: "$(params.git-repository-ref)"
          - name: git-commit
            value: "$(params.git-commit)"
          - name: git-author
            value: "$(params.git-author)"
          - name: git-message
            value: "$(params.git-message)"
        serviceAccountName: tekton-pipelines-sa
        timeout: "1h0m0s"

---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: gitlab-push-binding
  namespace: tekton-pipelines
spec:
  params:
    - name: git-repository-url
      value: "$(body.repository.git_http_url)"  # GitLab webhook repository URL
    - name: git-repository-ref
      value: "$(body.ref)"  # GitLab push ref (e.g., branch)
    - name: git-commit
      value: "$(body.after)"  # Git commit hash
    - name: git-author
      value: "$(body.user_name)"  # Git author (name of the user who pushed)
    - name: git-message
      value: "$(body.commits)"  # Git commit message

---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: gitlab-listener
  namespace: tekton-pipelines
spec:
  serviceAccountName: tekton-pipelines-sa  # The ServiceAccount to use for the EventListener
  triggers:
    - name: gitlab-push-trigger
      binding:
        ref: gitlab-push-binding
      template:
        ref: git-trigger-template
