controller:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  
  dashboard:
    enabled: true
    ingress:
      enabled: true
      hosts:
        - rollouts.samakia.lab
      annotations:
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
      tls:
        - hosts:
            - rollouts.samakia.lab
          secretName: rollouts-tls