apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: keycloak
  namespace: keycloak
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`keycloak.samakia.lab`)
      kind: Rule
      services:
        - name: keycloak
          port: 80
  tls:
    secretName: samakia-wildcard-tls
