apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: gitlab-listener
  namespace: tekton-pipelines
spec:
  serviceAccountName: tekton-pipelines-sa  # Service account used by the EventListener
  triggers:
    - name: gitlab-push-trigger
      interceptors:
        - ref:
            name: github
      bindings:
        - ref: gitlab-push-binding
      template:
        ref: gitlab-pipeline-template

---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: gitlab-push-binding
  namespace: tekton-pipelines
spec:
  params:
    - name: gitlab-repository
      value: "$(body.repository.name)"
    - name: gitlab-branch
      value: "$(body.ref)"
    - name: gitlab-commit
      value: "$(body.after)"
    - name: gitlab-author
      value: "$(body.user_name)"
    - name: gitlab-message
      value: "$(body.commits)"
    - name: gitlab-event
      value: "$(header.X-Gitlab-Event)"

---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: gitlab-pipeline-template
  namespace: tekton-pipelines
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: gitlab-pipeline-run-
      spec:
        pipelineRef:
          name: gitlab-pipeline  # Name of the Tekton pipeline to trigger
        serviceAccountName: tekton-pipelines-sa
        resources:
          - name: git-source
            resourceRef:
              name: gitlab-repository-resource
        params:
          - name: gitlab-commit
            value: "$(params.gitlab-commit)"
          - name: gitlab-branch
            value: "$(params.gitlab-branch)"
          - name: gitlab-author
            value: "$(params.gitlab-author)"
          - name: gitlab-message
            value: "$(params.gitlab-message)"
          - name: gitlab-event
            value: "$(params.gitlab-event)"
        timeout: "1h0m0s"  # Timeout for the pipeline run
