apiVersion: apps/v1
kind: Deployment
metadata:
  name: species
spec:
  replicas: 2
  selector:
    matchLabels:
      app: species
  template:
    metadata:
      labels:
        app: species
    spec:
      containers:
      - name: species
        image: your-registry/species:latest
