apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: samakia-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:ankouros/samakia-gitops.git
    targetRevision: main
    path: argo/apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
