apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: samakia-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:ankouros/samakia-gitops.git
    targetRevision: main
    path: argo/apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: samakia
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:ankouros/samakia-gitops.git
    targetRevision: main
    path: argo/apps/argo-rollouts
    helm:
      releaseName: argo-rollouts
  destination:
    server: https://kubernetes.default.svc
    namespace: samakia
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:ankouros/samakia-gitops.git
    targetRevision: main
    path: argo/apps/gitlab
    helm:
      releaseName: gitlab
  destination:
    server: https://kubernetes.default.svc
    namespace: samakia
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:ankouros/samakia-gitops.git
    targetRevision: main
    path: argo/apps/grafana
    helm:
      releaseName: grafana
  destination:
    server: https://kubernetes.default.svc
    namespace: samakia
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:ankouros/samakia-gitops.git
    targetRevision: main
    path: argo/apps/jenkins
    helm:
      releaseName: jenkins
  destination:
    server: https://kubernetes.default.svc
    namespace: samakia
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:ankouros/samakia-gitops.git
    targetRevision: main
    path: argo/apps/minio
    helm:
      releaseName: minio
  destination:
    server: https://kubernetes.default.svc
    namespace: samakia
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:ankouros/samakia-gitops.git
    targetRevision: main
    path: argo/apps/monitoring
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: samakia
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:ankouros/samakia-gitops.git
    targetRevision: main
    path: argo/apps/tekton
    helm:
      releaseName: tekton
  destination:
    server: https://kubernetes.default.svc
    namespace: samakia
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
