apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ankouros/samakia-gitops.git
    targetRevision: main
    path: argo/apps/tekton
    helm:
      releaseName: tekton
  destination:
    server: https://kubernetes.default.svc
    namespace: tekton
  syncPolicy:
    automated:
      prune: true
      selfHeal: true