apiVersion: apps/v1
kind: Deployment
metadata:
  name: pairs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pairs
  template:
    metadata:
      labels:
        app: pairs
    spec:
      containers:
      - name: pairs
        image: your-registry/pairs:latest
