apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-dev
  namespace: default
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/domain: vm-dev
    spec:
      domain:
        devices:
          disks:
          - name: containerdisk
            disk:
              bus: virtio
        resources:
          requests:
            memory: 2Gi
      volumes:
      - name: containerdisk
        containerDisk:
          image: registry:5000/kubevirt/cirros-container-disk-demo
      - name: cloudinitdisk
        cloudInitNoCloud:
          userData: |
            #cloud-config
            password: cirros
            chpasswd: { expire: False }
