apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: portainer
  namespace: portainer
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`portainer.samakia.lab`)
      kind: Rule
      services:
        - name: portainer
          port: 80
  tls:
    secretName: samakia-wildcard-tls
