apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: your-registry/portal
  newTag: latest-dev
patches:
- target:
    kind: Deployment
    name: portal
  patch: |
    - op: replace
      path: /spec/replicas
      value: 1
